// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSudoku.Data;

namespace WebSudoku.Migrations.User
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSudoku.Models.Board", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hints")
                        .HasColumnType("int");

                    b.Property<int>("Mistakes")
                        .HasColumnType("int");

                    b.Property<float>("Timer")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("WebSudoku.Models.Settings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("WebSudoku.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AvgTimeEasy")
                        .HasColumnType("real");

                    b.Property<float>("AvgTimeHard")
                        .HasColumnType("real");

                    b.Property<float>("AvgTimeMedium")
                        .HasColumnType("real");

                    b.Property<float>("BestTimeEasy")
                        .HasColumnType("real");

                    b.Property<float>("BestTimeHard")
                        .HasColumnType("real");

                    b.Property<float>("BestTimeMedium")
                        .HasColumnType("real");

                    b.Property<int?>("CurrentBoardID")
                        .HasColumnType("int");

                    b.Property<int>("GamesFinishedEasy")
                        .HasColumnType("int");

                    b.Property<int>("GamesFinishedHard")
                        .HasColumnType("int");

                    b.Property<int>("GamesFinishedMedium")
                        .HasColumnType("int");

                    b.Property<int?>("SettingsDataID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CurrentBoardID");

                    b.HasIndex("SettingsDataID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebSudoku.Models.User", b =>
                {
                    b.HasOne("WebSudoku.Models.Board", "CurrentBoard")
                        .WithMany()
                        .HasForeignKey("CurrentBoardID");

                    b.HasOne("WebSudoku.Models.Settings", "SettingsData")
                        .WithMany()
                        .HasForeignKey("SettingsDataID");

                    b.Navigation("CurrentBoard");

                    b.Navigation("SettingsData");
                });
#pragma warning restore 612, 618
        }
    }
}
